services:
  server:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - APP_TOKEN=${APP_TOKEN}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - SCHEMA=${SCHEMA}
      - BATCH_SIZE=${BATCH_SIZE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  postgres:
    image: postgres
    restart: always
    user: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOSTNAME}
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5 
volumes:
  db-data:
